### ISSUE TITLE
I tried 'install-php-extensions zookeeper' 

### ISSUE THREAD

**Issue by baipao123** [mlocati/docker-php-extension-installer#139]
but failed with 

```
pecl/zookeeper requires PHP (version >= 7.0.0, version <= 7.2.99), installed version is 7.4.1
```

how can I install zookeeper extension in php 7.4 ???

**Comment by mlocati** [comment]
At the moment it's not in the [list of supported extensions](https://github.com/mlocati/docker-php-extension-installer/blob/master/README.md#supported-php-extensions).

When I'll have some spare time I'll add support to it.

**Comment by caryxiao** [comment]
You can try it.
```bash
apt-get -y install libzookeeper-mt-dev && pecl install zookeeper && docker-php-ext-enable zookeeper
```

**Comment by mlocati** [comment]
I just added support to zookeeper (see #153): you can now install the zookeeper PHP extension simply with `install-php-extensions zookeeper`

> You can try it.
> 
> ```shell
> apt-get -y install libzookeeper-mt-dev && pecl install zookeeper && docker-php-ext-enable zookeeper
> ```

This is sub-optimal: your docker image will be a bit bigger than necessary, since the `libzookeeper-mt-dev` apt package is required only when installing the zookeeper PHP library, but it can be uninstalled when the PHP extension is installed.

A full script should be:
```sh
apt-get -y install libzookeeper-mt2 libzookeeper-mt-dev && \
pecl install zookeeper && \
docker-php-ext-enable zookeeper && \
apt-get remove --purge libzookeeper-mt-dev
```
