### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by shyim** [mlocati/docker-php-extension-installer#169]
PHP 8 Images does not contain pecl anymore. Any installation of xdebug, redis will fail

**Comment by mlocati** [comment]
https://github.com/mlocati/docker-php-extension-installer/pull/167 fixed this issue by using [pickle](https://github.com/FriendsOfPHP/pickle) instead of pecl (thanks again @mcfedr!).

BTW support for PHP 8 is still partial: some extensions are not yet ready for PHP 8: for example, we have to wait for XDebug version 3 and for [redis 5.3.2](https://github.com/phpredis/phpredis/issues/1842#issuecomment-689685626)

**Comment by shyim** [comment]
Maybe we can add something like `xdebug-git` or `redis-git`. I did compiled xdebug by my self with cloning the master. Did well for me :)

**Comment by mlocati** [comment]
https://github.com/mlocati/docker-php-extension-installer/pull/170 added support for XDebug with PHP 8

**Comment by mlocati** [comment]
https://github.com/mlocati/docker-php-extension-installer/pull/171 added support for redis with PHP 8
