### ISSUE TITLE
Install specific main version for extension

### ISSUE THREAD

**Issue by evs-xsarus** [mlocati/docker-php-extension-installer#243]
It's now possible to install a specific version for an extension, ie:
```
# Install Xdebug 2.x as 3.x is not yet supported by all applications.
RUN if [ "$version" = "5.6-cli" ]; then \
        install-php-extensions xdebug-2.5.5; \
    else \
        install-php-extensions xdebug-2.9.8; \
    fi
```

could this functionality be improved to support leaving out minor or patch versioning so this works:

```
install-php-extensions xdebug-2.5; \
```

or 

```
install-php-extensions xdebug-2; \
```

**Comment by mlocati** [comment]
This feature would require an additional step: before installing every package for which the user specifies a version (eg `xdebug-3` or `xdebug-3.0` or even `xdebug-3.0.1`) we'd need to fetch the list of all available versions.

For example, for xdebug, we'd need to:

- fetch https://pecl.php.net/rest/r/xdebug/allreleases.xml
- extract all the versions defined in that xml file
- check if the version provided by the user matches one of the existing versions
   - if so, we'd use that exact version
   - otherwise we have to cycle all available versions and:
      - extract the ones that start with the version provided by the user
      - pick the most recent ones of the above versions

**Comment by mlocati** [comment]
I have an idea: to avoid doing the above operations whenever users specify a version (eg `xedbug-3.0.1`), I'd introduce an alternative syntax: use `@` instead of `-` to tell the script that it have to look for the most recent compatible version.

For example:
- by using `-` you are specifying a full version (eg `xdebug-3.0.1`)
- by using `@` you are specifying a main version (eg `xdebug@3` or `xdebug@3.0`), and the script should look for the most recent version compatible with that one

Does this sound correct?

**Comment by evs-xsarus** [comment]
Might even be logical to implement this in Pickle ?

**Comment by mlocati** [comment]
> Might even be logical to implement this in Pickle ?

Two problems:

1. pickle is almost abandoned
2. we use pickle for PHP 8, but pecl for PHP 5.x and PHP 7.x
