### ISSUE TITLE
Support memcache for PHP 8.0

### ISSUE THREAD

**Issue by evs-xsarus** [mlocati/docker-php-extension-installer#244]
Currently, memcache can't be installed on PHP 8.0:

```
### INSTALLING REMOTE MODULE mcrypt ###
Downloading (100%)         est-stable): Downloading (connecting...)
+-----------------------------------+--------+
| Package name                      | mcrypt |
| Package version (current release) | 1.0.4  |
| Package status                    | stable |
+-----------------------------------+--------+
-### INSTALLING REMOTE MODULE memcache ###
Downloading (100%)         test-stable): Downloading (connecting...)

In Loader.php line 141:
                                                           
  Version mismatch - '4.0.5.2' != '8.0' in source vs. XML  
```

v8.x must be selected as shown on https://pecl.php.net/package-info.php?package=memcache&version=8.0

**Comment by mlocati** [comment]
It's a known issue (as reported in https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions).
The problem is that:
1. the latest version in the pecl repository is 8.0 (see https://pecl.php.net/package/memcache)
2. the latest version in the package.xml file is 4.0.5.2 (see https://github.com/websupport-sk/pecl-memcache/blob/8.0/package.xml#L49)
3. the latest version in the C source code is 4.0.5.2 (see https://github.com/websupport-sk/pecl-memcache/blob/8.0/src/php_memcache.h#L70)

When pickle download the extension, it sees that the two versions doesn't match, so it exits (with the message you reported here).

He have 3 solutions:
1. wait for a new memcache version
2. wait for a new pickle version which let us handle such issues (but I think it's not feasible: pickle seems almost abandoned)
3. update the install-php-extensions script to:
    1. manually download the memcache source archive
    2. extract that archive
    3. patch it
    4. compile and install memcache

The quick solution would be 3, but I'm a bit hesitant to do that: we'd need to keep track or it.

What about asking the memcache developers if they can publish a new version (or fix the source archive they published in the PECL repository)?
