### ISSUE TITLE
Request: Excimer

### ISSUE THREAD

**Issue by shyim** [mlocati/docker-php-extension-installer#283]
It Is a low overhead sampling profiler. 
Wiki: https://www.mediawiki.org/wiki/Excimer
Github: https://github.com/wikimedia/php-excimer

Works from 7.1-8.0

**Comment by mlocati** [comment]
Supporting extensions not published on pecl.php.net is a nightmare (we can't use pickle/pecl to install it, we don't have a package.xml file describing the requirements and the configure options, we have to manually check for new package versions, ...).

I'd ask them (probably @Krinkle or @tstarling) if they are going to publish the package on the pecl repository).

**Comment by tstarling** [comment]
I started a pecl-dev thread, since you're supposed to do that before creating a new package. Actually I posted to pecl-dev in 2019 but nobody replied, and I never got around to uploading the package. You need to be have a lot of energy to engage with PECL. I'll try to get Krinkle's PECL account approved, then he can be co-maintainer.

**Comment by mlocati** [comment]
Well, maybe we could ping @cmb69 in order to speedup the creation/approval of a PECL account...

**Comment by mlocati** [comment]
@tstarling any news?

**Comment by mlocati** [comment]
Done (see #309).

And PS: excimer is the 100th supported extension :wink:

**Comment by Krinkle** [comment]
Thanks all!
