### ISSUE TITLE
The README claims that memcached is not supported on PHP7.3... but it appears to work

### ISSUE THREAD

**Issue by yourpropertyexpert** [mlocati/docker-php-extension-installer#30]
I'm not sure whether the issue is "Well, Mark, you were lucky, but it's still not robust" ...
... or "oops - really ought to update the README" :-)

**Comment by mlocati** [comment]
Well, Mark, let's see what TravisCI says at https://travis-ci.org/mlocati/docker-php-extension-installer/builds/594657014 :wink:

**Comment by yourpropertyexpert** [comment]
It's been quite fun to watch someone else's CI run in real time :-)
But it passed :-)

**Comment by mlocati** [comment]
It seems that recent versions of memcached actually support PHP 7.3. See https://github.com/php-memcached-dev/php-memcached/releases.

Since I merged #31, the README has been updated automatically by https://travis-ci.org/mlocati/docker-php-extension-installer/builds/594659154

Thanks for reporting this 👍
