### ISSUE TITLE
PHP 8 - Alpine Linux - libzip purged with Composer despite PHP zip extension required

### ISSUE THREAD

**Issue by AymDev** [mlocati/docker-php-extension-installer#327]
Hi,

I am building an image based on `php:8.0.3-fpm-alpine` (Alpine Linux) and I use your script in its latest version (**1.2.23**).
During the firsts steps I install composer and some PHP extensions:
```sh
RUN apk update \
    && apk add --no-cache composer git nginx supervisor yarn \
    && install-php-extensions gd intl pdo_pgsql redis xdebug xsl zip \
    # ...
```

For the production image I delete **Composer** to reduce image size in the lasts steps:
```sh
RUN composer install --no-dev --no-interaction --optimize-autoloader \
    # ...
    && apk del composer git yarn \
    # ...
```

If I check the PHP version I get the following warning:
```sh
$ php --version
PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20200930/zip.so (Error loading shared library libzip.so.5: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20200930/zip.so)), /usr/locallib/php/extensions/no-debug-non-zts-20200930/zip.so.so 
(Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20200930/zip.so.so: No such file or directory)) in Unknown on line 0                                                                 
PHP 8.0.3 (cli) (built: Apr  1 2021 15:33:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

By looking at the CI logs it appears that a few needed packages are deleted with Composer:
```sh
(1/16) Purging composer (2.0.11-r0)
(2/16) Purging php7-phar (7.4.15-r0)
(3/16) Purging php7 (7.4.15-r0)
(4/16) Purging php7-curl (7.4.15-r0)
(5/16) Purging php7-iconv (7.4.15-r0)
(6/16) Purging php7-json (7.4.15-r0)
(7/16) Purging php7-mbstring (7.4.15-r0)
(8/16) Purging php7-openssl (7.4.15-r0)
(9/16) Purging php7-zip (7.4.15-r0)
(10/16) Purging php7-common (7.4.15-r0)
(11/16) Purging git (2.30.2-r0)
(12/16) Purging yarn (1.22.10-r0)
(13/16) Purging nodejs (14.16.1-r1)
(14/16) Purging pcre2 (10.36-r0)
(15/16) Purging libzip (1.7.3-r2)
(16/16) Purging c-ares (1.17.1-r1)
```

Is there an issue with the way the zip extension is installed ?
The [Alpine Linux documentation](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Remove_a_Package) states that `apk del` removes dependencies no longer needed but I don't know why it would consider libzip unnecessary.

Thank you for your work on this tool, it is very helpful.

**Comment by AymDev** [comment]
I just realized it removes `php7-zip` while I'm using PHP **8**. Maybe it should install `php8-zip` ? I installed it manually (`docker exec`), seems to work.

**Comment by mlocati** [comment]
Here's what's happening:

1. you install `composer`, which depends on `php7-zip`, which depends on `libzip`
2. you run `install-php-extensions zip`: since `install-php-extensions` sees that `libzip` is already installed, it doesn't install it
3. you remove `composer`, which uninstalls  `php7-zip` and  `libzip` (because apk thinks they are no more needed)

The solution is that `install-php-extensions` should call `apk add libzip` even if it's already installed.

I'll fix that as soon as I have some spare time.

In the meanwhile you can simply install composer with `install-php-extensions` (instead of using `apk add composer` simply add `@composer` to the extensions installed by `install-php-extensions`)

**Comment by AymDev** [comment]
Thank you for the clear explanation, now I get it.
It doesn't cause real bad issues for me right now but I'm gonna change the way I install composer anyways.

**Comment by mlocati** [comment]
> It doesn't cause real bad issues for me right now but I'm gonna change the way I install composer anyways.

Yep, installing it with `install-php-extensions` is much cleaner and faster

**Comment by yannoff** [comment]
@AymDev Here is what I learned from my own experience:  **never** use the distribution packages when it's about a  PHP frameworks or PHP related-tools

The reasons ?

Packages are frozen to an old, out-of-date version

And sadly, they're often poorly implemented...

That's no wonder: a PHP developper, as good as he could be, isn't expected to be an expert in Linux (not to mention the whole `APT` or `APK` ecosystem)

**Comment by mlocati** [comment]
I agree: PHP developers shouldn't have to learn system stuff like C/C++/gcc/bash/apt/apk/... it's really time consuming and error prone.

That's why I created this project.

Speaking for myself, I know all that stuff because of my 30+ years of experience in IT, but for sure PHP developers shouldn't be expected to have such a widespread knowledge

**Comment by mlocati** [comment]
Now everything is fine:

```
$ apk update
$ apk add composer
$ install-php-extensions zip
$ apk del composer
$ php --ri zip

zip

Zip => enabled
Zip version => 1.19.2
Libzip version => 1.7.3
BZIP2 compression => No
XZ compression => Yes
ZSTD compression => No
AES-128 encryption => Yes
AES-192 encryption => Yes
AES-256 encryption => Yes
```
