### ISSUE TITLE
php-src master does not build on Alpine

### ISSUE THREAD

**Issue by mvorisek** [mlocati/docker-php-extension-installer#582]
### Version of install-php-extensions

latest

### Error description

see https://github.com/php/php-src/issues/8681

the `sockets` ext needs newly `linux-headers` package on Alpine during the install

### Docker image

latest

**Comment by mlocati** [comment]
Here's a sample session, started with `docker run --rm -it ghcr.io/mvorisek/image-php:8.2-alpine-base sh`:

```
# curl -sSLf \
   -o /usr/local/bin/install-php-extensions \
   https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
# chmod +x /usr/local/bin/install-php-extensions
# install-php-extensions sockets
[...]
# php --ri sockets

sockets

Sockets Support => enabled
```

So, everything seems to work just fine...

**Comment by mvorisek** [comment]
You are right, the PHP 8.2 core image is built only when the complete (incl. foreign extensions) build passes.

I will improve the build process to push the core image immeditately after it is built. Would you be fine to include the image here for testing?

**Comment by mlocati** [comment]
> Would you be fine to include the image here for testing?

Nope, I really don't have time to maintain compatibility with custom docker images.

**Comment by mvorisek** [comment]
It is not a custom Docker image, it is basically the official `docker-library/php` Dockerfile /w php-src master source.

I do not think the time to maintain master compatibility would be much higher than the time needed to fix all the issues at once when a new PHP version is released.

As I need this installer to be compatible with master, I can put spent some time to fix all the issues /w bundled extensions. Would you be ok to merge such fixes incl. the testing /w the discussed image? If there will be too many fixes later needed, we can undo the testing /w the php-src master. It should be win-win for everyone.

**Comment by mlocati** [comment]
> It is not a custom Docker image

Official PHP docker images are available at https://hub.docker.com/_/php so , since your image is not available there, it's not an official image but a custom one :wink:

About your images here, we'd need to keep testing all the extensions for master at least daily (because the PHP source code may change and break stuff). That operation is very time consuming: we are already doing that for PHP 8.1 and it takes 1 hour and half.
Furthermore, if something doesn't work, I'd need to inspect what's going wrong. And since master is a development stage, it may be an issue related to PHP itself and not to the script.

I'd wait that PHP 8.1 published at least as an alpha (for PHP 8.1: the first Alpha has been published on 2021-06, that is 5 months before the official release).
If they follow the same scheduling, we should have a PHP 8.2 alpha version in a few days.

**Comment by mlocati** [comment]
I guess we are very near to an official 8.2 alpha release: they tagged it on 2022-06-07

**Comment by mlocati** [comment]
See #586

**Comment by mvorisek** [comment]
Are are ext tested one by one on a clean Docker image?

My CI with PHP 8.2 is still failing - see https://github.com/mvorisek/image-php/runs/6843213201?check_suite_focus=true#step:5:951

Actually I think there is a little logical issue with the installer. Please correct me if I am wrong, but it seems `./configure` is not run for each individual package, but the Docker image is configured with these deps - https://github.com/docker-library/php/blob/master/8.2-rc/alpine3.15/cli/Dockerfile#L101 - but there packages are removed after the php it build and the Docker image does not contain them, but the precomputed configure does still expect all of them.

**Comment by mlocati** [comment]
In #586 I didn't change the script: I've only tested all the extensions and added support for PHP 8.2 to the ones that already worked.
I'm planning to add more pull requests to add support to other extensions (like sockets).
The list of currently supported extensions per PHP version is always this one: https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions
