### ISSUE TITLE
Option to install all compatible extensions for version of PHP

### ISSUE THREAD

**Issue by mabed-fr** [mlocati/docker-php-extension-installer#628]
Hello

Option to install all compatible extensions is possible ?

Regards

**Comment by mlocati** [comment]
There's no such feature, and I don't plan to implement it.

In order to get the list of all the extensions available for specific PHP versions you can [take a look at the README file](https://github.com/mlocati/docker-php-extension-installer/#supported-php-extensions): you can simply copy that table data.

If you need to do some automated processing, you could use of the [`data/supported-extensions`](https://github.com/mlocati/docker-php-extension-installer/blob/master/data/supported-extensions) file, but please take also a look at the [`data/special-requirements`](https://github.com/mlocati/docker-php-extension-installer/blob/master/data/special-requirements) file.
