### ISSUE TITLE
45min to install grpc

### ISSUE THREAD

**Issue by mentamarindos** [mlocati/docker-php-extension-installer#691]
### Version of install-php-extensions

latest

### Error description

It takes 45min to install grpc extension ... try to build the dockerfile to reproduce the issue

### Docker image

php:8.1-cli

### Minimal Dockerfile

```Dockerfile
FROM php:8.1-fpm-buster

RUN mkdir -p /var/www/html

WORKDIR /var/www/html

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN docker-php-ext-install pdo pdo_mysql

RUN apt-get update \ 
    && apt-get install autoconf zlib1g-dev -y

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions protobuf grpc 
RUN docker-php-ext-enable protobuf
RUN docker-php-ext-enable grpc
    

CMD ["php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "-R"]
```

**Comment by mlocati** [comment]
First of all, a few notes about your dockerfile:

1. you don't need to manually install the apt packages: `install-php-extensions` will do that for you.
   That saves some disk space: `install-php-extensions` will install the apt packages required to compile PHP extensions, then compiles the PHP extensions, and finally uninstall them (since they are required only to build extensions)
2. you don't need to call `docker-php-ext-enable`: `install-php-extensions` will do that for you
3. `install-php-extensions` [can install composer too](https://github.com/mlocati/docker-php-extension-installer#installing-composer)
4. you can use `install-php-extensions` instead of `docker-php-ext-install`

So, your dockerfile can be simplified as

```Dockerfile
FROM php:8.1-fpm-buster

RUN mkdir -p /var/www/html

WORKDIR /var/www/html

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions @composer pdo pdo_mysql protobuf grpc 

CMD ["php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "-R"]
```

About the time required to build grpc...

Here's what I have in my system:

```sh
$ time install-php-extensions grpc
[...]
real    1m38.864s
user    23m13.668s
sys     2m9.030s
```

So, it requires about 1 minute and 39 seconds for me. You can try to increase the number of processors of your machine, or use a faster machine.

Finally, this project is *only* a wrapper for the `pecl` and `docker-php-ext-...` commands, there's really nothing I can do about compilation of specific PHP extensions (and indeed grpc is a rather big extension).
