### ISSUE TITLE
missing extension and support (php8.1-fpm)

### ISSUE THREAD

**Issue by rsidhaarth** [mlocati/docker-php-extension-installer#719]
Hi,

Can you please add support for the PHP extension for php8.1-fpm

1) common
2) cli
3) CGI
4) mysql

**Comment by mlocati** [comment]
> 1. common
> 2. cli
> 3. CGI

Those are not PHP extensions.
I guess you are referring to the system packages provided by apt and/or apk.
They are included in the Docker images (for example, in the  `php:8.1-fpm` docker image you can run the `php` command, which you may be referring to as `cli`)

> 4. mysql

The mysql PHP extension has been deprecated and is no more available since PHP 5.6.
You should use the `mysqli` extension (or `pdo_mysql`).
