### ISSUE TITLE
redis with lz4

### ISSUE THREAD

**Issue by cloud-arrow** [mlocati/docker-php-extension-installer#777]
Why does redis not support lz4

<img width="356" alt="截屏2023-07-30 09 53 17" src="https://github.com/mlocati/docker-php-extension-installer/assets/52516729/6810d53a-e1a5-4e07-8b09-ac5276a9fa9c">

**Comment by cloud-arrow** [comment]
@mlocati

**Comment by mlocati** [comment]
@cloud-arrow  I'm having a break these days

**Comment by mlocati** [comment]
In order to install redis with lz4 support using the PECL command (which is the way `install-php-extensions` installs PHP extensions), the redis PHP extension must be updated with [this change](https://github.com/phpredis/phpredis/pull/2366).

So, you have to wait that phpredis maintainers review that change and publish a new version [on pecl](https://pecl.php.net/package/redis).

**Comment by mlocati** [comment]
This is now fixed (you'll require at least PHP 7.2)
