### ISSUE TITLE
Cannot install swoole using php:8.3-zts-alpine (linux/arm/v7) 

### ISSUE THREAD

**Issue by shinsenter** [mlocati/docker-php-extension-installer#875]
### Version of install-php-extensions

v2.1.80

### Error description

The same issue with #873 but for `php:8.3-zts-alpine`.

Build command:

```bash
docker build --platform=linux/arm/v7 -f Dockerfile .
```

### Docker image

php:8.3-zts-alpine

### Minimal Dockerfile

```Dockerfile
FROM --platform=linux/arm/v7 php:8.3-zts-alpine

# IPE default settings
ARG IPE_ASPELL_LANGUAGES=en
ARG IPE_GD_WITHOUTAVIF=1
ARG IPE_ICU_EN_ONLY=1
ARG IPE_INSTANTCLIENT_BASIC=1
ARG IPE_KEEP_SYSPKG_CACHE=0
ARG IPE_LZF_BETTERCOMPRESSION=1

ARG IPE_SOURCE=https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions
ADD --chmod=755 $IPE_SOURCE /usr/local/bin/

RUN set -ex && install-php-extensions swoole
```

**Comment by mlocati** [comment]
I did a quick search for you:

- you have to use swoole 5.0 on 32-bit systems - see https://github.com/swoole/swoole-src/issues/5198#issuecomment-1820162178
- swoole supports PHP 8.3 since version 5.1 - see https://pecl.php.net/package-changelog.php?package=swoole&amp;release=5.1.1

I don't see any solution, except contacting the swoole maintainers...

**Comment by shinsenter** [comment]
@mlocati 

I apologize for any inconvenience.
I appreciate your support. You’re doing a fantastic job with this tool.
